### ISSUE TITLE
Not able to update

### ISSUE THREAD

**Issue by andrewchumchal** [limetech/dockerapp-plex#6]
I recently updated to unRAID 6.2 and with that I had to update most of my dockers apps. When I went to update plex. It came out with this error. Any ideas what can fix this ? `Error: layers from manifest don't match image configuration`

**Comment by eschultz** [comment]
You will need to delete your docker.img file and recreate it again: Settings —> Docker —> Enable Docker: No —> Apply —> Toggle on ‘Advanced View’ near the top-right —> Tick on the ‘Delete Image File’ checkbox —> Delete —> Enable Docker: Yes —> Apply.  

You can then reinstall your docker apps through the my\* templates (or from Community Application's Previous Apps section if you have that plugin installed).  Your apps will be back the exact same way as before, with no adjustment of the volume mappings, ports, etc required.  This is a one-time operation.

There may be other tips and advice for upgrading to 6.2 here: http://lime-technology.com/forum/index.php?topic=51874.msg497876#msg497876

**Comment by andrewchumchal** [comment]
Why did this happen though?

**Comment by jonfairbanks** [comment]
FYI: 'Delete Image File' does not appear to be an option in 6.2. Probably needs to be done over SSH now.

**Comment by eschultz** [comment]
![screen shot 2016-10-09 at 8 32 30 pm](https://cloud.githubusercontent.com/assets/390064/19225346/828dceea-8e60-11e6-99aa-5a1be9728d63.png)
'Delete Image File' is still in 6.2.  It's visible once you stop Docker and toggle on Advanced View.

**Comment by eschultz** [comment]
@andrewchumchal It's complicated but i'll do my best to try to explain it.  

Docker migrated to a newer API / storage backend for all the Docker containers almost a year ago and has been maintaining the old and new backends up until a couple months ago.  
The problem was the 'layer ids' that made up Plex, for example, in the old backend didn't match the same layer ids for Plex in the new backend, even though the contents were the same.  So time went on and we kept pushing out updates for our Plex container.  Eventually the old backend stopped getting the Plex updates when Docker stopped maintaining the old backend.  At that point, unRAID 6.1 (older version of Docker), would use the old backend to pull down layers.  So when you pulled down Plex initially it used the layer ids from the old backend.  Some of the layers, like ubuntu, are probably even "shared" with other installed containers.  
When you upgraded to unRAID 6.2 (new Docker version) there were now updates available for Plex because the new backend was being used by default.  The Plex update, now coming from the new backend, only needed to pull down a couple of the updated layers.  It skips the ubuntu base layer because it's already installed but that's the problem since the ubuntu base layer (and possibly other intermediate layers in Plex?) have the old layer ids but the new Plex container expects all layers to have ids from the new backend you get a `Error: layers from manifest don't match image configuration`
Instead of deleting the docker.img, you could alternatively fix this issue by deleting any other container that shares a layer or base image with Plex, essentially purging out layers with old ids,  but it's a little tricky to tell which containers do (or maybe all?).  So much easier to delete the docker.img and be done with it... at least until Docker decides to migrate to another backend/API again 😢

**Comment by andrewchumchal** [comment]
@eschultz  Thanks for your reply. I understand. Thanks for all you do
